# Generated by Django 2.0.7 on 2018-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=50, unique=True)),
                ('bpub_date', models.DateField()),
                ('sub_date', models.DateTimeField()),
                ('bread', models.IntegerField(default=0)),
                ('bcomment', models.IntegerField(default=0)),
                ('idDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('hgender', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('hcontent', models.CharField(max_length=500)),
            ],
        ),
    ]
